### PR TITLE
switch to ubuntu:bionic base image

### PR DESCRIPTION
**Pull request by chenbh**
Part of concourse/concourse#3266

Image size is now 25.9mb -> 110mb

### CODE REVIEW

**Comment by zachgersh** [comment]
@chenbh done - seems pretty straight forward. Would have been nice to note if you had built the image using the dockerfile now.

**Comment by chenbh** [comment]
Hey @zachgersh, it turns out this will not be going in the next release, do you want me to reopen the branch and open a PR to revert this change?

**Comment by chenbh** [comment]
The concourse team is going to keep using `alpine` on `master` branch for now, we will be maintaining a `bionic-base-image` branch for releases to pivnet

**Comment by zachgersh** [comment]
Yes please! Thank you

**Pull request merged**
